create admins(
    id
    login
    password
)
schools(
    id
    name
    login
    password
)
parents(
    id
    phone
    telegram_id
    password
)

--oxirigacha yitkizish kerak
create table attendance(
    id int generated by default as identity primary key,
    name
)
attendance (
    id
    name
    file
    school_id
)

create database nvms; \c nvms

create table admins(
    id int generated by default as identity primary key,
    role smallint not null default 0,
    username varchar(40) not null,
    password varchar(64) not null
);

alter table admins add column school varchar(40) not null;
ALTER TABLE admins 
ADD COLUMN school VARCHAR(40) NOT NULL;
create unique index username_index on admins(lower(username));

create table schools(
    id int generated by default as identity primary key,
    name varchar(100) not null,
    login varchar(40) not null,
    password varchar(64) not null
);
create unique index login_index on schools(lower(login));

create table parents(
    id int generated by default as identity primary key,
    phone varchar(20) not null,
    password varchar(64) not null,
    telegram_id int,
    step smallint not null default 0,
    school_id int not null references schools(id)
);
create unique index phone_index on parents(phone);

create extension pgcrypto;

insert into admins (username, password, role, school) values ('admin', crypt('1234', gen_salt('bf')), 1, 118);
insert into schools (name, login, password) values ('118-maktab', "118", crypt('111', gen_salt('bf')));