-- create admins(
--     id
--     login
--     password
-- )
-- schools(
--     id
--     name
--     login
--     password
-- )
-- parents(
--     id
--     phone
--     telegram_id
--     password
-- )

--oxirigacha yitkizish kerak
create table attendance(
    id int generated by default as identity primary key,
    name
)
attendance (
    id
    name
    file
    school_id
)


---------------------------------
--new database version

create database nvms_d;
\c nvms_d

create table admins(
    id int generated by default as identity primary key,
    role smallint not null default 0,
    login varchar(40) not null,
    password varchar(64) not null,
    school varchar(40) not null
);
create unique index admin_index on admins(lower(login));

create table schools(
    id int generated by default as identity primary key,
    name varchar(100) not null,
    login varchar(40) not null,
    password varchar(64) not null
);
create unique index school_index on schools(lower(login));

create table classes(
    id int generated by default as identity primary key,
    class varchar(10) not null,
    school_id int not null references schools(id)
);
create unique index class_index on classes(lower(class), school_id);

create table parents(
    parent VARCHAR(100) not null
    id int generated by default as identity primary key,
    phone varchar(20) not null,
    password varchar(64) not null,
    telegram_id int,
    step smallint not null default 0,
    class_id int not null references classes(id)
);
create unique index phone_index on parents(phone);

--insert value
create extension pgcrypto;

insert into admins (role, login, password, school) values (1, 'admin', crypt('1234', gen_salt('bf')), 118);
insert into schools (name, login, password) values ('120-maktab', '120', crypt('2222', gen_salt('bf')));

--
/*
    VAPSHE NEW
*/

create database nvms_x;
\c nvms_x

create table admins(
    admin_id int generated by default as identity primary key,
    role smallint not null default 0,
    login varchar(40) not null,
    password varchar(64) not null
);
create unique index admin_index on admins(lower(login));

create table schools(
    school_id int generated by default as identity primary key,
    name varchar(100) not null,
    login varchar(40) not null,
    password varchar(64) not null
);
create unique index school_index on schools(lower(login));

create table classes(
    class_id int generated by default as identity primary key,
    class varchar(10) not null,
    school_id int not null,
    constraint fk_school
        FOREIGN key (school_id)
            references schools(school_id)
            on delete cascade
);
create unique index class_index on classes(lower(class), school_id);

create table parents(
    parent_id int generated by default as identity primary key,
    parent VARCHAR(100) not null,
    phone varchar(20) not null,
    password varchar(64) not null,
    telegram_id int,
    step smallint not null default 0,
    class_id int not null,
    constraint fk_class
        FOREIGN key (class_id)
            references classes(class_id)
            on delete cascade
);
create unique index phone_index on parents(phone);

--insert value
create extension pgcrypto;

insert into admins (role, login, password) values (1, 'admin', crypt('1234', gen_salt('bf')));

insert into schools (name, login, password) values ('118-maktab', '118', crypt('1111', gen_salt('bf')));
insert into schools (name, login, password) values ('120-maktab', '120', crypt('2222', gen_salt('bf')));